name: Continuous Integration

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Check out
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up .NET
      uses: actions/setup-dotnet@v4

    - name: Restore
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Test
      run: dotnet test --configuration Release --no-build --logger "trx;LogFileName=test-results.trx"

    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      if: success() || failure()
      with:
        name: test-results
        path: tests/NGuid.Tests/TestResults/test-results.trx

    - name: Pack
      run: dotnet pack --configuration Release --no-build

    - name: Upload NuGet Package
      uses: actions/upload-artifact@v4
      with:
        name: nuget
        path: artifacts/package/release/
        if-no-files-found: error
